# Generated by Django 4.0.1 on 2022-01-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN_number_10',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN_number_13',
            field=models.CharField(max_length=13),
        ),
    ]
