# Generated by Django 4.0.1 on 2022-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0002_alter_book_isbn_number_10_alter_book_isbn_number_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN_number_10',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN_number_13',
            field=models.CharField(max_length=20),
        ),
    ]
