# Generated by Django 4.0.1 on 2022-01-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0003_alter_book_isbn_number_10_alter_book_isbn_number_13'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN_number_10',
            new_name='ISBN_10',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ISBN_number_13',
        ),
    ]
