# Generated by Django 4.0.1 on 2022-01-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0004_rename_isbn_number_10_book_isbn_10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN_10',
            new_name='ISBN_number',
        ),
    ]
