# Generated by Django 4.0.1 on 2022-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0005_rename_isbn_10_book_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True),
        ),
    ]
