# Generated by Django 4.0.1 on 2022-01-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0016_alter_book_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
