# Generated by Django 4.0.1 on 2022-01-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0018_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
