# Generated by Django 4.0.1 on 2022-01-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0020_alter_book_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(blank=True, default='https://code-artisan.io/wp-content/uploads/2020/12/default_book_cover_2015.jpg', max_length=255),
        ),
    ]
