# Generated by Django 4.0.1 on 2022-01-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0023_author_remove_book_authors_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default='ja', max_length=200),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
