# Generated by Django 4.0.1 on 2022-01-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_books', '0024_remove_book_authors_book_authors_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=200),
        ),
    ]
